networks:
  nginx-network:
    driver: bridge

services:
  express-api-1:
    build: './express-api'
    image: 'express-api-image'
    networks:
      - nginx-network
    volumes:
      - './express-api:/express-api'
    environment:
      - PORT=${EXPRESS_API_PORT_1}
    mem_limit: '256m'
    cpus: '0.5'
    cpuset: '2'
  
  express-api-2:
    build: './express-api'
    image: 'express-api-image'
    networks:
      - nginx-network
    volumes:
      - './express-api:/express-api'
    environment:
      - PORT=${EXPRESS_API_PORT_2}
    mem_limit: '256m'
    cpus: '0.5'
    cpuset: '3'

  express-api-3:
    build: './express-api'
    image: 'express-api-image'
    networks:
      - nginx-network
    volumes:
      - './express-api:/express-api'
    environment:
      - PORT=${EXPRESS_API_PORT_3}
    mem_limit: '256m'
    cpus: '0.5'
    cpuset: '4'

  website:
    build: './website'
    image: 'website-image'
    networks:
      - nginx-network
    volumes:
      - './website:/website'
    mem_limit: '512m'
    cpus: '1'
    cpuset: '1'

  load_balancer:
    image: nginx
    networks:
      - nginx-network
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 5000:80
    mem_limit: '128m'
    cpus: '1'
    cpuset: '0'
    depends_on:
      - express-api
      - website
